server:
 port: 8085

cloud-consumer:
 ribbon:
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
 level:
  com.alibaba.nacos.client.naming: error

#熔断器配置
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      #设置API网关中路由转发请求的HystrixCommand执行超时时间
      timeoutInMilliseconds: 1

spring:
 cloud:
  gateway:
   default-filters:
   routes:
    - id: cloud-consumer
      uri: lb://cloud-consumer
      predicates:
       - Path=/**/**
      filters:
#       开启熔断，返回失败信息
#       - Hystrix=myCommandName
       # 熔断后进行处理
       - name: Hystrix
         args:
          name: failTestOut
          fallbackUri: forward:/testOutFail

 zipkin:
  base-url: http://192.168.9.198:9411/
  discovery-client-enabled: false
 sleuth:
  sampler:
   probability: 1

management:
 endpoints:
  web:
   exposure:
    include: '*'
  endpoint:
   health:
    show-details: ALWAYS