#服务端口
server:
 port: 9001
person:
  name: yhl
  gender: male
  age: 18

logging:
 level:
  com.service: INFO
  com.alibaba.nacos.client.naming: error

spring:
 zipkin:
  base-url: http://192.168.9.198:9411/
  discovery-client-enabled: false
 sleuth:
  sampler:
   probability: 1