server:
  port: 8080
# \u8BBE\u7F6E\u5BF9\u670D\u52A1\u63D0\u4F9B\u8005\u7684\u8D1F\u8F7D\u5747\u8861\u7B56\u7565
cloud-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    com.consumer: debug
#feign:
#  hystrix:
#    enabled: true
feign:
  httpclient:
    connection-timeout: 10000
